language: node_js
node_js:
  - "7"
cache: yarn
install:
  - yarn install
  - yarn global add surge now

jobs:
  include:
    - stage: test
      script: yarn test
    - stage: publish
      script:
        - ./deploy.sh
    - script:
        - surge --project ./build --domain rock-the-open-source.surge.sh
    - script:
        - ./now_deploy.sh
